public class Main {
    public static void main(String[] args) {
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        var friend = 19.0;
        System.out.println(friend);
        friend = friend * 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var firstBoxer = 78.2;
        var secondBoxer = 82.7;
        var weight = firstBoxer + secondBoxer;
        System.out.println("Общий вес спортсменов составляет " + weight + " кг!");
        var difWeight = secondBoxer - firstBoxer;
        System.out.println("Вес первого бойца меньше, чем вес второго на " + difWeight + " кг!");
        difWeight = secondBoxer % firstBoxer;
        System.out.println("Вес первого бойца меньше, чем вес второго на " + difWeight + " кг!");
        var hours = 640;
        var onePersonHour=8;
        var amount = hours/onePersonHour;
        System.out.println("Всего работников в компании – " + amount +  " человек");
        amount = amount + 94;
        hours = amount * 8;
        System.out.println("Если в компании работает " + amount + " человека, то всего " + hours + " часов работы может быть поделено между сотрудниками");
    }
}